<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1Places</name>
   <tag></tag>
   <elementGuidId>a9189ec2-19dc-46a1-9e30-63528431a988</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.tyi4kqb.atm_c8_fkimz8.atm_g3_11yl58k.atm_fr_4ym3tx.atm_cs_qo5vgd.dir.dir-ltr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='site-content']/div/div/div/div/div/section/h1/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6629e161-c994-4b76-bb55-305c885932b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tyi4kqb atm_c8_fkimz8 atm_g3_11yl58k atm_fr_4ym3tx atm_cs_qo5vgd dir dir-ltr</value>
      <webElementGuid>ad687478-9929-43ac-bfe1-97b09ff0b010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search resultsOver 1,000 places in Kuala Lumpur</value>
      <webElementGuid>4b8f790b-fda3-46f0-b9a2-b92f61ac612e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-content&quot;)/div[@class=&quot;l196t2l1 atm_gz_k75hcd atm_h0_k75hcd atm_gz_wwb3ei__oggzyc atm_h0_wwb3ei__oggzyc atm_gz_k75hcd__1v156lz atm_h0_k75hcd__1v156lz dir dir-ltr&quot;]/div[@class=&quot;f14cvyw1 atm_gq_k75hcd atm_h3_k75hcd dir dir-ltr&quot;]/div[@class=&quot;c1yo0219 atm_9s_1txwivl_vmtskl atm_92_1yyfdc7_vmtskl atm_9s_1txwivl_9in345 atm_92_1yyfdc7_9in345 dir dir-ltr&quot;]/div[1]/div[@class=&quot;t17a5psn atm_9s_1txwivl atm_ar_1bp4okc atm_cx_z1y8gd dir dir-ltr&quot;]/section[1]/h1[@class=&quot;hpipapi atm_7l_1kw7nm4 atm_c8_1x4eueo atm_cs_1kw7nm4 atm_g3_1kw7nm4 atm_gi_idpfg4 atm_l8_idpfg4 atm_kd_idpfg4_pfnrn2 dir dir-ltr&quot;]/span[@class=&quot;tyi4kqb atm_c8_fkimz8 atm_g3_11yl58k atm_fr_4ym3tx atm_cs_qo5vgd dir dir-ltr&quot;]</value>
      <webElementGuid>4a0ec4d2-43c4-4405-8424-9b61255fdaa0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-content']/div/div/div/div/div/section/h1/span</value>
      <webElementGuid>b25f4418-372c-4631-88c5-fe09ea58551a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/span</value>
      <webElementGuid>94e4fa4d-5e2f-45cd-807f-1c1b32eb280c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Search resultsOver 1,000 places in Kuala Lumpur' or . = 'Search resultsOver 1,000 places in Kuala Lumpur')]</value>
      <webElementGuid>7c82b820-1a9f-491e-8631-a75417ebec86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
