<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputSearhDestination</name>
   <tag></tag>
   <elementGuidId>ab29de7e-c8b6-45c9-bda4-399537e2a50b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bigsearch-query-location-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bigsearch-query-location-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f017f4e9-3f57-474f-9714-176cf18d9994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ihrdk2j atm_9s_1ulexfb atm_3f_idpfg4 atm_gi_idpfg4 atm_l8_idpfg4 atm_vy_1osqo2v atm_26_glywfm atm_c8_fkimz8 atm_g3_11yl58k atm_fr_4ym3tx atm_cs_qo5vgd atm_7l_18pqv07 atm_sq_1l2sidv atm_c8_fkimz8_17x46du atm_g3_11yl58k_17x46du atm_fr_4ym3tx_17x46du atm_cs_atq67q_17x46du atm_7l_o7x4t6_17x46du atm_c8_fkimz8_y5ttn9 atm_g3_11yl58k_y5ttn9 atm_fr_4ym3tx_y5ttn9 atm_cs_atq67q_y5ttn9 atm_7l_o7x4t6_y5ttn9 atm_c8_fkimz8_1k1obal atm_g3_11yl58k_1k1obal atm_fr_4ym3tx_1k1obal atm_cs_atq67q_1k1obal atm_7l_o7x4t6_1k1obal atm_c8_fkimz8_m14rgb atm_g3_11yl58k_m14rgb atm_fr_4ym3tx_m14rgb atm_cs_atq67q_m14rgb atm_7l_o7x4t6_m14rgb atm_c8_fkimz8_3ykvna atm_g3_11yl58k_3ykvna atm_fr_4ym3tx_3ykvna atm_cs_atq67q_3ykvna atm_7l_o7x4t6_3ykvna atm_9s_glywfm_136h51u atm_kd_glywfm_pfnrn2 atm_ll_1fwxnve_c2x6ez dir dir-ltr</value>
      <webElementGuid>413d98ea-7e55-446c-ae3c-91eba377d58d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>21a68e27-e1aa-4ba9-9bc6-5fcad828a4fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a0d92d95-2cb9-4a81-bae7-c1b722471360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5f5e7bfc-9dbb-4e86-90c4-db2c17880b5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5ae76573-deeb-4d29-b89b-c074f7b51aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bigsearch-query-location-input</value>
      <webElementGuid>3d634443-f8e3-4618-8a54-c58a612bf7c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>query</value>
      <webElementGuid>9c05f1c7-6263-4b6d-991a-4be147345424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>bigsearch-query-location-description</value>
      <webElementGuid>7e398034-ec27-4dfe-aded-390b6700f3d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search destinations</value>
      <webElementGuid>57135c76-23ce-4b02-83f7-a7d17229673c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>structured-search-input-field-query</value>
      <webElementGuid>c9b44163-01e9-4e23-9d46-ac33f32e42da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bigsearch-query-location-input&quot;)</value>
      <webElementGuid>39f66b28-1f49-45e7-ba6d-2dac36be397e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bigsearch-query-location-input']</value>
      <webElementGuid>c9a60725-9a4c-4f1f-8c17-3d6f70b6dd9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-tabpanel']/div/div/div/label/div/input</value>
      <webElementGuid>73c1332a-a7ad-4c21-8de3-e822b18a752d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div/input</value>
      <webElementGuid>3fb45cc7-0c6c-4869-9aac-ac8c5afd5de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'bigsearch-query-location-input' and @name = 'query' and @placeholder = 'Search destinations']</value>
      <webElementGuid>8fc8a748-dd86-46b0-ac5d-6d5b99e1123d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
